# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locks',
            fields=[
                ('lock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('lock_date_start', models.DateTimeField()),
                ('lock_date_end', models.DateTimeField()),
            ],
            options={
                'db_table': 'locks',
                'managed': False,
            },
        ),
    ]
