# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certifications',
            fields=[
                ('certificaion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('certification_name', models.CharField(max_length=45)),
                ('certification_path', models.CharField(blank=True, max_length=45, null=True)),
                ('certificacion_institution', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'certifications',
                'managed': False,
            },
        ),
    ]
