# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesionals',
            fields=[
                ('profesional_id', models.AutoField(primary_key=True, serialize=False)),
                ('profesional_name', models.CharField(max_length=45)),
                ('profesional_description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'profesionals',
                'managed': False,
            },
        ),
    ]
