# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypePayment',
            fields=[
                ('type_payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_payment_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'type_payment',
                'managed': False,
            },
        ),
    ]
