# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkouts',
            fields=[
                ('checkout_id', models.IntegerField(primary_key=True, serialize=False)),
                ('checkout_observation', models.CharField(max_length=45)),
                ('checkout_code_transaction', models.CharField(max_length=45)),
                ('checkout_token', models.CharField(blank=True, max_length=45, null=True)),
                ('checkout_authorization_code', models.CharField(blank=True, max_length=45, null=True)),
                ('checkout_payment_type_code', models.CharField(blank=True, max_length=45, null=True)),
                ('checkout_buy_order', models.CharField(blank=True, max_length=45, null=True)),
                ('checkout_vci', models.CharField(blank=True, max_length=45, null=True)),
                ('checkout_card_detail', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'checkouts',
                'managed': False,
            },
        ),
    ]
