# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('servicio_break', models.IntegerField()),
                ('service_weeks_enable', models.IntegerField()),
                ('service_price', models.FloatField()),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
    ]
