# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_start', models.TimeField()),
                ('schedule_end', models.TimeField()),
                ('schedule_day', models.IntegerField()),
                ('schedule_status', models.IntegerField()),
            ],
            options={
                'db_table': 'schedules',
                'managed': False,
            },
        ),
    ]
