# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('specialty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('specialty_name', models.CharField(max_length=45)),
                ('specialty_description', models.CharField(max_length=45)),
                ('trial132', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'specialties',
                'managed': False,
            },
        ),
    ]
