# Generated by Django 4.2.4 on 2023-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=45)),
                ('institution_mail', models.CharField(blank=True, max_length=45, null=True)),
                ('institution_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('institution_state_id', models.IntegerField(blank=True, null=True)),
                ('institution_city_id', models.IntegerField(blank=True, null=True)),
                ('institution_street', models.CharField(blank=True, max_length=45, null=True)),
                ('institution_lat', models.CharField(blank=True, max_length=45, null=True)),
                ('institution_lon', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'institutions',
                'managed': False,
            },
        ),
    ]
