# Generated by Django 4.2.4 on 2023-08-15 12:53

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=45)),
                ('user_email', models.CharField(max_length=45)),
                ('user_rut', models.IntegerField()),
                ('user_dv', models.CharField(max_length=45)),
                ('user_phone', models.CharField(max_length=45)),
                ('user_password', models.CharField(max_length=45)),
                ('user_lastname', models.CharField(max_length=45)),
                ('user_mother_last_name', models.CharField(max_length=45)),
                ('user_avatar', models.CharField(max_length=45)),
                ('user_delete', models.IntegerField()),
                ('user_token_login', models.CharField(blank=True, max_length=45, null=True)),
                ('user_token_reset', models.CharField(blank=True, max_length=45, null=True)),
                ('user_nationality', models.CharField(blank=True, max_length=45, null=True)),
                ('user_profession_id', models.IntegerField(blank=True, null=True)),
                ('user_birthdate', models.DateTimeField()),
                ('user_insurance', models.IntegerField(blank=True, null=True)),
                ('user_num_sis', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
